version: '3.8'

services:
  easyfinance:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
    env_file:
      - .env  # Carrega as variáveis de ambiente do arquivo .env
    networks:
      - easyfinance_network
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - easyfinance_network

networks:
  easyfinance_network:
    driver: bridge
